Config = {
        MenuLanguage = 'en',	
}
    -- Duration will be a random duration between the min and max.
    Config.inspectDurationMin = 5000 --miliseconds
    Config.inspectDurationMax = 25000 --miliseconds

    Config.searchDurationMin = 5000 --miliseconds
    Config.searchDurationMax = 15000 --miliseconds

    Config.KeybindKeys = {
        ['Q'] = 44,
        ['G'] = 47,
        ['X'] = 73,
        ['E'] = 38,
        ['H'] = 104,
        ['num9'] = 118
    }
    
Config.Languages = {
    ['en'] = {
        ['keys_message'] = 'Press ~INPUT_PICKUP~ to inspect body or ~INPUT_VEH_SHUFFLE~ to search where the damage occurred.',
        ['not_dead'] = 'This player is not dead.',
        ['no_bone_broke'] = 'You cant find where te damage occurred.',
        ['unknown'] = 'The dead cause is unknown to you.',

        ['drown'] = 'This person has alot of water in his lungs, he must of drowned.',
        ['fall'] = 'It seems like this this body hit the ground at a high speed.',
        
        ['vehicle'] = 'This person got hit by a vehicle.',
        ['aircraft'] = '8',
        ['lazer_explosive_canon'] = '8',
        ['car_drown'] = '8',
        ['helicopter_minigun'] = '8',
        ['helicopter_explosive_ammo'] = '8',
        ['helicopter_rocket'] = '8',
        ['plane_turret'] = '8',
        ['technical_turret'] = '8',
        ['insurgent_turret'] = '8',
        ['anti_aircraft_turret'] = '8',
        ['20mm_flak_turret'] = '8',
        ['20mm_autocannon'] = '8',
        ['pistol'] = '0',
        ['micro_smg'] = '0',
        ['marksman_pistol'] = '0',
        ['assault_rifle'] = '0',
        ['double_barrel_shotgun'] = '0',
        ['pump_shotgun'] = '0',
        ['grenade'] = '0',
        ['ap_pistol'] = '0',
        ['gusenberg_sweeper'] = '0',
        ['combat_mg'] = '0',
        ['flare_gun'] = '0',
        ['gasoline'] = '0',
        ['molotov'] = '0',
        ['heavy_sniper'] = '0',
        ['heavy_sniper_mk2'] = '0',
        ['marksman_rifle'] = '0',
        ['marksman_rifle_mk2'] = '0',
        ['rpg'] = '0',
        ['explosion'] = '0',
        ['minigun'] = '0',
        ['water_cannon'] = '0',
        ['anitique_cavalry_dagger'] = '0',
        ['golf_club'] = '0',
        ['crowbar'] = '0',
        ['baseball_bat'] = '0',
        ['hamer'] = '0',
        ['nightstick'] = '0',
        ['knife'] = '0',
        ['fist'] = '0',
        ['switchblade'] = '0',
        ['flashlight'] = '0',
        ['firework_launcher'] = '0',
        ['sniper_rifle'] = '0',
        ['sns_pistol'] = '0',
        ['smg'] = '0',
        ['mg'] = '0',
        ['assault_smg'] = '0',
        ['combat_pistol'] = '0',
        ['heavy_pistol'] = '0',
        ['heavy_shotgun'] = '0',
        ['assault_shotgun'] = '0',
        ['bullpup_shotgun'] = '0',
        ['musket'] = '0',
        ['sawed_off_shotgun'] = '0',
        ['grenade_launcher'] = '0',
        ['compact_grenade_launcher'] = '0',
        ['homing_launcher'] = '0',
        ['compact_rifle'] = '0',
        ['bullpup_rifle'] = '0',
        ['advanced_rifle'] = '0',
        ['carbine_rifle'] = '0',
        ['special_carbine'] = '0',
        ['combat_PDW'] = '0',
        ['mini_smg'] = '0',
        ['tear_gas'] = '0',
        ['.50_pistol'] = '0',
        ['vintage_pistol'] = '0',
        ['heavy_revolver'] = '0',
        ['machine_pistol'] = '0',
        ['assault_rifle_mk2'] = '0',
        ['smg_mk2'] = '0',
        ['pump_shotgun_mk2'] = '0',
        ['special_carbine_mk2'] = '0',
        ['carbine_rifle_mk2'] = '0',
        ['sns_pistol_mk2'] = '0',
        ['pistol_mk2'] = '0',
        ['double_action_revolver'] = '0',
        ['pipe_bomb'] = '0',
        ['bullpup_rifle_mk2'] = '0',
        ['heavy_revolver_mk2'] = '0',
        ['railgun'] = '0',
        ['sticky_bomb'] = '0',
        ['Proximity_mine'] = '0',
        ['pipe_wrench'] = '0',
        ['pool_cue'] = '0',
        ['snowball'] = '0',
        ['battle_axe'] = '0',
        ['machete'] = '0',
        ['kuckle_duster'] = '0',
        ['hatchet'] = '0',
        ['bottle'] = '0',
        ['stone_hatchet'] = '0',
        ['widowmaker'] = '0',
        ['unholy_hellbringer'] = '0',
        ['up_n_atomizer'] = '0',
        ['rotweiler_shepard'] = '0',
        ['retriver_husky'] = '0',
    },

    ['fr'] = {
        ['server_start'] = 'fr',
        ['fall'] = 'Je mappelle fale!',
    },

    ['de'] = {
        ['server_start'] = 'de',
    },

    ['sv'] = {
        ['server_start'] = 'sv',
    },

    ['es'] = {
        ['server_start'] = "es",
    }
}